<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/* if($_SERVER['HTTP_HOST']==('localhost' || '192.168.0.144' || '192.168.0.13' || '192.168.0.18'))
{	
	ini_set('display_errors', 1);
	error_reporting(E_ALL);
}else{
	error_reporting(0);
} */

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/

$config['project_name'] = 'LivewireCRM';
$config['sitename'] = 'LivewireCRM';
$config['admin_email'] = 'nishit.modi@tops-int.com';



$uriSegments = explode('index.php',$_SERVER['PHP_SELF']);



$config['base_url'] = 'http://'.$_SERVER['HTTP_HOST'].$uriSegments[0];
$config['date_time_zone']='EST';
$config['amount_sign']='$';
$config['joomla_webservice_link'] = 'http://prod.seattlerealestatetoday.com';//'http://seattle.livewiresites.com';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']	= 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9=~%.:_\-:`@-';
//$config['permitted_uri_chars'] = '';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']		= TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']	= 'c';
$config['function_trigger']		= 'm';
$config['directory_trigger']	= 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';
$config['common_date_format'] = 'm/d/Y';
//$config['common_date_format1'] = 'Y-m-d';
$config['common_datetime_format'] = 'm/d/Y h:i A';
$config['common_time_format'] = 'h:i A';
//$config['common_datetime_format1'] = 'Y-m-d h:i AM';



/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = 'abcd5435423aderst';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'		= the name you want for the cookie
| 'sess_expiration'			= the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'	= Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'		= Whether to encrypt the cookie
| 'sess_use_database'		= Whether to save the session data to a database
| 'sess_table_name'			= The name of the session database table
| 'sess_match_ip'			= Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'	= Whether to match the User Agent when reading the session data
| 'sess_time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']		= 'leadsession';
$config['sess_expiration']		= 7200;
$config['sess_expire_on_close']	= FALSE;
$config['sess_encrypt_cookie']	= TRUE;
$config['sess_use_database']	= FALSE;
$config['sess_table_name']		= 'ci_sessions';
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update']	= 300;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix']	= "";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';

//view type
$config['front_view']= 'front';
$config['admin_view']= 'admin';
//Defining custom paths
$config['admin_css_path']= $config['base_url']."css/admin/";
$config['css_path']= $config['base_url']."css/";

$config['admin_js_path']= $config['base_url']."js/admin/";

$config['js_path']= $config['base_url']."js/";

$config['listing_path']= $config['base_url']."listing_assets/";

$config['admin_base_url'] = $config['base_url'].$config['index_page'].'admin/';
$config['superadmin_base_url'] = $config['base_url'].$config['index_page'].'superadmin/';
$config['user_base_url'] = $config['base_url'].$config['index_page'].'user/';
$config['ck_editor_path']= $config['base_url']."ckeditor/";

$config['base_path'] = $_SERVER['DOCUMENT_ROOT'];
$config['base_path'] .= preg_replace('@/+$@','',dirname($_SERVER['SCRIPT_NAME'])).'';
$config['image_path']= $config['base_url']."images/";

$config['image_file_path']= $_SERVER['DOCUMENT_ROOT'].'/'.$config['project_name']."/images/";
$config['upload_image_file_path']= $_SERVER['DOCUMENT_ROOT'].$uriSegments[0]."uploads/";

$config['upload_img_path']= $config['base_url']."uploads/";

$config['temp_big_img_basepath']=$config['base_path']."uploads/temp/big/";
$config['temp_small_img_basepath']=$config['base_path']."uploads/temp/small/";
$config['temp_big_img_path']="uploads/temp/big/";
$config['temp_small_img_path']="uploads/temp/small/";

$config['contact_big_img_path']=$config['base_path']."/uploads/contact/big/";
$config['contact_small_img_path']=$config['base_path']."/uploads/contact/small/";
$config['contact_upload_img_big']= $config['base_url']."uploads/contact/big/";
$config['contact_upload_img_small']= $config['base_url']."uploads/contact/small/";
$config['contact_small_upload_img_path']="/uploads/contact/big/";
$config['contact_big_uplode_img_path']="/uploads/contact/small/";

$config['child_big_img_base_path'] = $config['base_path']."/livewire_child_website/uploads/admin/big/";
$config['child_small_img_base_path'] = $config['base_path']."/livewire_child_website/uploads/admin/small/";

$config['admin_big_img_path']=$config['base_path']."/uploads/admin/big/";
$config['admin_small_img_path']=$config['base_path']."/uploads/admin/small/";
$config['admin_upload_img_big']= $config['base_url']."uploads/admin/big/";
$config['admin_upload_img_small']= $config['base_url']."uploads/admin/small/";
$config['admin_small_upload_img_path']="/uploads/admin/big/";
$config['admin_big_uplode_img_path']="/uploads/admin/small/";

$config['download_csv_path']= $config['base_url']."uploads/contact_csv/sample/Sample_CSV.csv";
$config['download_property_csv_sample']= $config['base_url']."uploads/contact_csv/sample/property_sample_csv.csv";
$config['contact_documents_big_img_path']=$config['base_path']."/uploads/contact_docs/";
$config['contact_documents_img_path']="uploads/contact_docs/";

$config['listing_documents_big_img_path']=$config['base_path']."/uploads/listing_docs/";
$config['listing_documents_img_path']="uploads/listing_docs/";


$config['listing_big_img_path']=$config['base_path']."/uploads/listing/big/";
$config['listing_small_img_path']=$config['base_path']."/uploads/listing/small/";
$config['listing_upload_img_big']= $config['base_url']."uploads/listing/big/";
$config['listing_upload_img_small']= $config['base_url']."uploads/listing/small/";
$config['listing_small_upload_img_path']="/uploads/listing/big/";
$config['listing_big_uplode_img_path']="/uploads/listing/small/";


$config['contact_documents_csv_path']="uploads/contact_csv/";
$config['contact_documents_big_csv_path']=$config['base_path']."/uploads/contact_csv/";

$config['mls_documents_csv_path']="uploads/mls_csv/";
$config['mls_documents_big_csv_path']=$config['base_path']."/uploads/mls_csv/";
$config['temp_path']=$config['base_path']."/uploads/temp/";
$config['user_big_img_path']=$config['base_path']."/uploads/user/big/";
$config['user_small_img_path']=$config['base_path']."/uploads/user/small/";
$config['user_upload_img_big']= $config['base_url']."uploads/user/big/";
$config['user_upload_img_small']= $config['base_url']."uploads/user/small/";
$config['user_small_upload_img_path']="/uploads/user/big/";
$config['user_big_uplode_img_path']="/uploads/user/small/";

$config['broker_big_img_path']=$config['base_path']."/uploads/broker/big/";
$config['broker_small_img_path']=$config['base_path']."/uploads/broker/small/";
$config['broker_upload_img_big']= $config['base_url']."uploads/broker/big/";
$config['broker_upload_img_small']= $config['base_url']."uploads/broker/small/";
$config['broker_small_upload_img_path']="/uploads/broker/big/";
$config['broker_big_uplode_img_path']="/uploads/broker/small/";

$config['ck_editor_path']= $config['base_url']."ckeditor/";
//calendar
$config['wdcalendar']= $config['base_url']."wdcalendar/";
$config['cal_path']= $config['base_url']."calendar/";
$config['email_param_pattern']= '{(%s)}';
$config['attachment_file'] = $config['base_url']."uploads/attachment_file/";
$config['attachment_basepath_file'] = $config['base_path']."/uploads/attachment_file/";
$config['attachment_temp_basepath'] = $config['base_path']."/uploads/attachment_temp/";
$config['attachment_temp'] = $config['base_url']."uploads/attachment_temp/";
$config['temp_attachment_path'] =  "uploads/attachment_temp/";
$config['smtp_host']       = 'mail.made4mediagroup.com';
$config['smtp_user']       = 'hello@game7.pt';
$config['smtp_pass']       = 'G7mailbox';
$config['mailtype']        ='html';
$config['newline']         ="\r\n";
$config['smtp_port']       = '25';
$config['upload_file']= $config['base_path']."/uploads/attachment_file/";

// Default TimeZone
$config['default_timezone'] = "America/New_York";

//SMS Send

$config['from_sms']= '+15084554748';
$config['from_to']= '+919033921029';

//MLS credentials
$config['mls_userid']= 'livewire';
$config['mls_password']= 'VtGO8j5h5';

// Listing manager base path
$config['proprty_listing_base_path']=$config['base_url']."property_listing/";


$config['livewire_db_conditions'] = ($_SERVER['HTTP_HOST']=='104.130.170.161' || $_SERVER['HTTP_HOST']=='104.130.236.55' || $_SERVER['HTTP_HOST']=='104.130.5.42' || $_SERVER['HTTP_HOST']=='104.130.162.47' || $_SERVER['HTTP_HOST']=='104.130.31.5' || $_SERVER['HTTP_HOST']=='crmwa.thelivewiresolution.com' || $_SERVER['HTTP_HOST']=='www.crmwa.thelivewiresolution.com' || $_SERVER['HTTP_HOST']=='thelivewiresolution.com' || $_SERVER['HTTP_HOST']=='www.thelivewiresolution.com' || $_SERVER['HTTP_HOST']=='mylivewiresolution.com' || $_SERVER['HTTP_HOST']=='www.mylivewiresolution.com');

//$config['livewire_db_conditions'] = ($_SERVER['HTTP_HOST']=='104.130.31.5' || $_SERVER['HTTP_HOST']=='crmwa.thelivewiresolution.com' || $_SERVER['HTTP_HOST']=='www.crmwa.thelivewiresolution.com' || $_SERVER['HTTP_HOST']=='thelivewiresolution.com' || $_SERVER['HTTP_HOST']=='www.thelivewiresolution.com' || 'mylivewiresolution.com' || 'www.mylivewiresolution.com');

$config['topsin_db_conditions'] = ($_SERVER['HTTP_HOST']=='topsdemo.in' || $_SERVER['HTTP_HOST']=='www.topsdemo.in' || $_SERVER['HTTP_HOST']=='livewire.topsdemo.in' || $_SERVER['HTTP_HOST']=='www.livewire.topsdemo.in');
$config['local_db_conditions'] = ($_SERVER['HTTP_HOST']==('localhost' || '192.168.0.17' ||'192.168.0.18' || '192.168.0.20' || '192.168.0.28' || '192.168.0.126' || '192.168.0.130'));

$config['livewire_staging_db_conditions'] = ($_SERVER['HTTP_HOST']=='tst.livewireleads.com' || $_SERVER['HTTP_HOST']=='www.tst.livewireleads.com');

$config['livewire_staging_db2_conditions'] = ($_SERVER['HTTP_HOST']=='104.239.226.210' || $_SERVER['HTTP_HOST']=='104.130.229.199' || $_SERVER['HTTP_HOST']=='livewirecloud.com' || $_SERVER['HTTP_HOST']=='www.livewirecloud.com' || $_SERVER['HTTP_HOST']=='m.livewirecloud.com' || $_SERVER['HTTP_HOST']=='LIVEWIRECLOUD.COM' || $_SERVER['HTTP_HOST']=='WWW.LIVEWIRECLOUD.COM');

//For one to many

if($config['livewire_db_conditions']){

	$config['parent_db_name'] = 'CRM';
	$config['parent_db_prefix'] = 'CRM_';
	$config['parent_db_user_prefix'] = 'livewire_';
	
	$config['root_host_name'] = 'd6ff2f329eb5275cdd6de6652edead79053c6d0f.rackspaceclouddb.com';
	$config['root_host_name_for_create_db_user'] = '%';
	//$config['root_host_name'] = 'localhost';
	$config['root_user_name'] = 'root';
	$config['root_password'] = 'tMQMhYb2pCCUAqKzkCVUzNjW68JrwTFcuJUZ';
	
	//Linked In access token
	$config['linkedin_api_key'] = '78e38kuvn4jnta';
	$config['linkedin_secret_key'] = 'pUDH0wD6wZCrKorU';
	
	$config['linkedin_api_key_user'] = '78jg2pubxaft1e';
	$config['linkedin_secret_key_user'] = 'fgHgeAvuOpCItgkB';
		
	$config['twitter_access_key'] = 'dqv9A8ENH6bHKoVavpFbc62Mr';
	$config['twitter_secret_key'] = 'asbyjyZ5OTOOxmdNSUwNzg9zU93QXSI7GazpXBUqzVFR4Gg2tc';
	$config['twitter_callback_url'] = $config['base_url'].'admin/social_account_master/twitter_callback';
	
	//user twitter api
	$config['twitter_access_key_user'] = 'UwFaaE6NfktoBfHrVtphbx8Ul';
	$config['twitter_secret_key_user'] = 'ccXbzqU8eNkdMutVzks48zMk5JiPkBpJYS5TUyp0slO4NnXjJD';
	$config['twitter_callback_url_user'] = $config['base_url'].'user/social_account_master/twitter_callback';
	
	//facebook
	
	$config['facebook_api_key'] = '476872102451409';
	$config['facebook_secret_key'] = '5655027eef7e4ea09ed91e643b3e8983';
	
	//Google
	
	$config['google_access_key'] = '550949170093-pi7h3ejnfh3b2edrub2rr7eghbp6053m.apps.googleusercontent.com';
	$config['google_secret_key'] = 'nw_u0lPJXFzfyKoz_zZHHbpB';
	$config['google_callback_url'] = $config['base_url'].'admin/social_account_master/import_google_contact/';
	
	//User google credential
	$config['google_access_key_user'] = '243859996629-smtp95o6n1na4kh87mus3fa4d4i6caia.apps.googleusercontent.com';
	$config['google_secret_key_user'] = 'hgi6P-a4JJZ2w-_L4Eqt9Vsj';
	$config['google_callback_url_user'] = $config['base_url'].'user/social_account_master/import_google_contact/';
	
	//Admin Google Calendar Credential
	
	$config['google_calendar_client_id'] = '221408618253-hoacuihkq0aorgp420ej9fmcskb8lls3.apps.googleusercontent.com';
	$config['google_calendar_client_secret'] = 'vLLlxC7XVMBjd6r1eCsN7gse';
	$config['google_calendar_redirect_uri'] = $config['base_url'].'admin/calendar/google_connection';
	
	//User Google Calendar Credential
	$config['google_calendar_redirect_uri_user'] = $config['base_url'].'user/calendar/google_connection';
	$config['email_send_from'] = 'mailgun';
	
	//MlS database
	$config['mls_staging_db'] 		= 'CRM_staging_db';
	$config['mls_staging_host'] 	= 'd6ff2f329eb5275cdd6de6652edead79053c6d0f.rackspaceclouddb.com';
	$config['mls_staging_username'] = 'root';
	$config['mls_staging_password'] = 'tMQMhYb2pCCUAqKzkCVUzNjW68JrwTFcuJUZ';
	
	$config['mls_master_db']  		= 'CRM_mls_master_db';
	$config['mls_master_host']  	= 'd6ff2f329eb5275cdd6de6652edead79053c6d0f.rackspaceclouddb.com';
	$config['mls_master_username']  = 'root';
	$config['mls_master_password']  = 'tMQMhYb2pCCUAqKzkCVUzNjW68JrwTFcuJUZ';

	$config['ns_record_details'] = 'dns1.stabletransit.com<br>dns2.stabletransit.com';
	
}elseif($config['topsin_db_conditions']){

	$config['parent_db_name'] = 'topsin_live_crm';
	$config['parent_db_prefix'] = 'topsin_live_crm_';
	$config['parent_db_user_prefix'] = 'topsin_u_';
	
	$config['root_host_name'] = 'localhost';
	$config['root_host_name_for_create_db_user'] = 'localhost';
	$config['root_user_name'] = 'root';
	$config['root_password'] = 'ToPs@tops$$';
	//Linked In access token
	$config['linkedin_api_key'] = '756clqbj6t9epz';
	$config['linkedin_secret_key'] = 'EAtBLXiWKWbISQ8Y';
	
	$config['linkedin_api_key_user'] = '781dfcsirakn3s';
	$config['linkedin_secret_key_user'] = 'HkrsjGNvwVQqhjKS';
	//twitter
	/*$config['twitter_access_key'] = 'c3WpMzmy77K7PmauiE0USKPGC';
	$config['twitter_secret_key'] = 'AhzwZeXLY1FKvS1GSoheRxdXs7XiNhDLoPBkPEYn4DdMFisQkJ';
	$config['twitter_callback_url'] = $config['base_url'].'admin/social_account_master/twitter_callback';*/
	
	$config['twitter_access_key'] = 'cjfX5rzCxQhNtwDxRRiyBKPm2';
	$config['twitter_secret_key'] = 'sQznH9xphdeEyNBOTtWjVZddBXGTNIWXsJ9Z9UR00mwqcs4pTN';
	$config['twitter_callback_url'] = $config['base_url'].'admin/social_account_master/twitter_callback';
	
	//user twitter api
	$config['twitter_access_key_user'] = 'svUINSuTjiNDwckaHvMbVR2R3';
	$config['twitter_secret_key_user'] = 'wdUoYz4c0vuVH29Bh3CnJ0jfRYAMr4gMgJQmxraMArgKBoWBhy';
	$config['twitter_callback_url_user'] = $config['base_url'].'user/social_account_master/twitter_callback';
	//facebook
	/*$config['facebook_api_key'] = '990949044292689';
	$config['facebook_secret_key'] = 'c17d9bb5b6de31f1cb61cf880a019629';*/
	
	$config['facebook_api_key'] = '406463062855261';
	$config['facebook_secret_key'] = 'b954c2ff761e885d495a8cb54be7bd9a';
	
	//Google
	
	$config['google_access_key'] = '147648857715-1mld5plcdbvcnhum9p48mg3vcod434pi.apps.googleusercontent.com';
	$config['google_secret_key'] = '2pS0dOkG9IvWcD491Ro_Lzke';
	$config['google_callback_url'] = $config['base_url'].'admin/social_account_master/import_google_contact/';
	
	//User google credential
	$config['google_access_key_user'] = '147648857715-es9pqgsmol9f83fvkkhol2df6c1725u3.apps.googleusercontent.com';
	$config['google_secret_key_user'] = 'bgOoXVYnK8r1QQAtk1qvZuz-';
	$config['google_callback_url_user'] = $config['base_url'].'user/social_account_master/import_google_contact/';
	
	//Admin Google Calendar Credential
	
	$config['google_calendar_client_id'] = '550560099620-15in47epip5gmk0b1qvbabmgc6rq5vpv.apps.googleusercontent.com';
	$config['google_calendar_client_secret'] = 'Cp3YLlJLWM5o4f1J_-z1EBKY';
	$config['google_calendar_redirect_uri'] = $config['base_url'].'admin/calendar/google_connection';
	
	//User Google Calendar Credential
	$config['google_calendar_redirect_uri_user'] = $config['base_url'].'user/calendar/google_connection';
	$config['email_send_from'] = 'smtp';

	//MlS database
	$config['mls_staging_db'] 		= 'topsin_livewire_staging_database';
	$config['mls_staging_host'] 	= 'localhost';
	$config['mls_staging_username'] = 'root';
	$config['mls_staging_password'] = 'ToPs@tops$$';
	
	$config['mls_master_db']  		= 'topsin_livewire_mls_master_database';
	$config['mls_master_host']  	= 'localhost';
	$config['mls_master_username']  = 'root';
	$config['mls_master_password']  = 'ToPs@tops$$';
	$config['ns_record_details'] = 'ns1.topsdemo.in<br>ns2.topsdemo.in';
	
}
elseif($config['livewire_staging_db_conditions']){

	$config['parent_db_name'] = 'CRM_livewire';
	$config['parent_db_prefix'] = 'CRM_';
	$config['parent_db_user_prefix'] = 'livewire_';
	
	$config['root_host_name'] = '4eaf1896ce34df85a81401f970fdd8f51dd1d8bb.rackspaceclouddb.com';
	$config['root_host_name_for_create_db_user'] = '%';
	//$config['root_host_name'] = 'localhost';
	$config['root_user_name'] = 'crm_staging_user';
	$config['root_password'] = 'crm@123';
	
	//Linked In access token
	$config['linkedin_api_key'] = '78e38kuvn4jnta';
	$config['linkedin_secret_key'] = 'pUDH0wD6wZCrKorU';
	
	$config['linkedin_api_key_user'] = '78jg2pubxaft1e';
	$config['linkedin_secret_key_user'] = 'fgHgeAvuOpCItgkB';
		
	$config['twitter_access_key'] = 'dqv9A8ENH6bHKoVavpFbc62Mr';
	$config['twitter_secret_key'] = 'asbyjyZ5OTOOxmdNSUwNzg9zU93QXSI7GazpXBUqzVFR4Gg2tc';
	$config['twitter_callback_url'] = $config['base_url'].'admin/social_account_master/twitter_callback';
	
	//user twitter api
	$config['twitter_access_key_user'] = 'UwFaaE6NfktoBfHrVtphbx8Ul';
	$config['twitter_secret_key_user'] = 'ccXbzqU8eNkdMutVzks48zMk5JiPkBpJYS5TUyp0slO4NnXjJD';
	$config['twitter_callback_url_user'] = $config['base_url'].'user/social_account_master/twitter_callback';
	
	//facebook
	
	$config['facebook_api_key'] = '476872102451409';
	$config['facebook_secret_key'] = '5655027eef7e4ea09ed91e643b3e8983';
	
	//Google
	
	$config['google_access_key'] = '550949170093-pi7h3ejnfh3b2edrub2rr7eghbp6053m.apps.googleusercontent.com';
	$config['google_secret_key'] = 'nw_u0lPJXFzfyKoz_zZHHbpB';
	$config['google_callback_url'] = $config['base_url'].'admin/social_account_master/import_google_contact/';
	
	//User google credential
	$config['google_access_key_user'] = '243859996629-smtp95o6n1na4kh87mus3fa4d4i6caia.apps.googleusercontent.com';
	$config['google_secret_key_user'] = 'hgi6P-a4JJZ2w-_L4Eqt9Vsj';
	$config['google_callback_url_user'] = $config['base_url'].'user/social_account_master/import_google_contact/';
	
	//Admin Google Calendar Credential
	
	$config['google_calendar_client_id'] = '221408618253-hoacuihkq0aorgp420ej9fmcskb8lls3.apps.googleusercontent.com';
	$config['google_calendar_client_secret'] = 'vLLlxC7XVMBjd6r1eCsN7gse';
	$config['google_calendar_redirect_uri'] = $config['base_url'].'admin/calendar/google_connection';
	
	//User Google Calendar Credential
	$config['google_calendar_redirect_uri_user'] = $config['base_url'].'user/calendar/google_connection';
	$config['email_send_from'] = 'mailgun';
	
	//MlS database
	$config['mls_staging_db'] 		= 'CRM_staging_livewireleads';
	$config['mls_staging_host'] 	= '4eaf1896ce34df85a81401f970fdd8f51dd1d8bb.rackspaceclouddb.com';
	$config['mls_staging_username'] = 'crm_staging_user';
	$config['mls_staging_password'] = 'crm@123';
	
	$config['mls_master_db']  		= 'CRM_mls_master_db_livewireleads';
	$config['mls_master_host']  	= '4eaf1896ce34df85a81401f970fdd8f51dd1d8bb.rackspaceclouddb.com';
	$config['mls_master_username']  = 'crm_staging_user';
	$config['mls_master_password']  = 'crm@123';

	$config['ns_record_details'] = 'dns1.stabletransit.com<br>dns2.stabletransit.com';
	
}
elseif($config['livewire_staging_db2_conditions']){

	$config['parent_db_name'] = 'CRM_mylivewiresolution';
	$config['parent_db_prefix'] = 'CRM_';
	$config['parent_db_user_prefix'] = 'livewire_';
	
	$config['root_host_name'] = '4eaf1896ce34df85a81401f970fdd8f51dd1d8bb.rackspaceclouddb.com';
	$config['root_host_name_for_create_db_user'] = '%';
	//$config['root_host_name'] = 'localhost';
	$config['root_user_name'] = 'crm_staging_user';
	$config['root_password'] = 'crm@123';
	
	//Linked In access token
	$config['linkedin_api_key'] = '78e38kuvn4jnta';
	$config['linkedin_secret_key'] = 'pUDH0wD6wZCrKorU';
	
	$config['linkedin_api_key_user'] = '78jg2pubxaft1e';
	$config['linkedin_secret_key_user'] = 'fgHgeAvuOpCItgkB';
		
	$config['twitter_access_key'] = 'dqv9A8ENH6bHKoVavpFbc62Mr';
	$config['twitter_secret_key'] = 'asbyjyZ5OTOOxmdNSUwNzg9zU93QXSI7GazpXBUqzVFR4Gg2tc';
	$config['twitter_callback_url'] = $config['base_url'].'admin/social_account_master/twitter_callback';
	
	//user twitter api
	$config['twitter_access_key_user'] = 'UwFaaE6NfktoBfHrVtphbx8Ul';
	$config['twitter_secret_key_user'] = 'ccXbzqU8eNkdMutVzks48zMk5JiPkBpJYS5TUyp0slO4NnXjJD';
	$config['twitter_callback_url_user'] = $config['base_url'].'user/social_account_master/twitter_callback';
	
	//facebook
	
	$config['facebook_api_key'] = '476872102451409';
	$config['facebook_secret_key'] = '5655027eef7e4ea09ed91e643b3e8983';
	
	//Google
	
	$config['google_access_key'] = '550949170093-pi7h3ejnfh3b2edrub2rr7eghbp6053m.apps.googleusercontent.com';
	$config['google_secret_key'] = 'nw_u0lPJXFzfyKoz_zZHHbpB';
	$config['google_callback_url'] = $config['base_url'].'admin/social_account_master/import_google_contact/';
	
	//User google credential
	$config['google_access_key_user'] = '243859996629-smtp95o6n1na4kh87mus3fa4d4i6caia.apps.googleusercontent.com';
	$config['google_secret_key_user'] = 'hgi6P-a4JJZ2w-_L4Eqt9Vsj';
	$config['google_callback_url_user'] = $config['base_url'].'user/social_account_master/import_google_contact/';
	
	//Admin Google Calendar Credential
	
	$config['google_calendar_client_id'] = '221408618253-hoacuihkq0aorgp420ej9fmcskb8lls3.apps.googleusercontent.com';
	$config['google_calendar_client_secret'] = 'vLLlxC7XVMBjd6r1eCsN7gse';
	$config['google_calendar_redirect_uri'] = $config['base_url'].'admin/calendar/google_connection';
	
	//User Google Calendar Credential
	$config['google_calendar_redirect_uri_user'] = $config['base_url'].'user/calendar/google_connection';
	$config['email_send_from'] = 'mailgun';
	
	//MlS database
	$config['mls_staging_db'] 		= 'CRM_staging_livewireleads';
	$config['mls_staging_host'] 	= '4eaf1896ce34df85a81401f970fdd8f51dd1d8bb.rackspaceclouddb.com';
	$config['mls_staging_username'] = 'crm_staging_user';
	$config['mls_staging_password'] = 'crm@123';
	
	$config['mls_master_db']  		= 'CRM_mls_master_db_livewireleads';
	$config['mls_master_host']  	= '4eaf1896ce34df85a81401f970fdd8f51dd1d8bb.rackspaceclouddb.com';
	$config['mls_master_username']  = 'crm_staging_user';
	$config['mls_master_password']  = 'crm@123';

	$config['ns_record_details'] = 'dns1.stabletransit.com<br>dns2.stabletransit.com';
	
}elseif($config['local_db_conditions']){

	$config['parent_db_name'] = 'topsin_live_crm';
	$config['parent_db_prefix'] = 'livewire_crm_';
	$config['parent_db_user_prefix'] = 'topsin_l_u_';
	
	$config['root_host_name'] = 'localhost';
	$config['root_host_name_for_create_db_user'] = 'localhost';
	$config['root_user_name'] = 'root';
	$config['root_password'] = '';
	//Linked In access token
	$config['linkedin_api_key'] = '751zz5h45afzge';
	$config['linkedin_secret_key'] = 'EFOLDTjLbjqBgTNQ';
	
	$config['linkedin_api_key_user'] = '786x4nevnmcvc4';
	$config['linkedin_secret_key_user'] = 'Hj8kmrJct9iR2ziE';
	
	//$config['linkedin_api_key'] = '75cpfi3yaw4esz';
	//$config['linkedin_secret_key'] = 'ZtGQqlUQwUrNXqGa';
	
	//twitter key
	$config['twitter_access_key'] = 'EBxwrYhxKJ6248tRg9KYdMSbj';
	$config['twitter_secret_key'] = 'RoWD2otQSmv5dCWMfg6ZKQq5Uh9MzSW4JDqf199r0wRHfxnE0z';
	$config['twitter_callback_url'] = $config['base_url'].'admin/social_account_master/twitter_callback';
	
	//user twitter api
	$config['twitter_access_key_user'] = 'QfywPSrsH6WZ100ZV6LtNQ51g';
	$config['twitter_secret_key_user'] = '5M3g9nFZ1U5WZiEo6eT57s6YP4meyYJJvMUa3lb3BPiQStF6qf';
	$config['twitter_callback_url_user'] = $config['base_url'].'user/social_account_master/twitter_callback';
	
	//facebook
	$config['facebook_api_key'] = '728901530477590';
	$config['facebook_secret_key'] = '450e78a3c48a4731e4d8c2592c2bbae1';
	
	$config['google_access_key'] = '159584468093-tin7bmvoh88059bo9ndaafhqkvm432j7.apps.googleusercontent.com';
	$config['google_secret_key'] = 'fR0v8P3rVwOwtmO2I_fEuc5y';
	$config['google_callback_url'] = $config['base_url'].'admin/social_account_master/import_google_contact';
	
	//User google credential
	$config['google_access_key_user'] = '296779585587-u8qp2op16g9hl789vuatkcm0i6c10b0j.apps.googleusercontent.com';
	$config['google_secret_key_user'] = '-4uyj0YlX0S9OqmZ_hhvKNsg';
	$config['google_callback_url_user'] = $config['base_url'].'user/social_account_master/import_google_contact/';
	
	//Admin Google Calendar Credential
	
	$config['google_calendar_client_id'] = '353776521294-77pbclq72746aev176rvlf6msa4b49i0.apps.googleusercontent.com';
	$config['google_calendar_client_secret'] = '_KPzyQNoECP6iC-1qkakWNiI';
	$config['google_calendar_redirect_uri'] = $config['base_url'].'admin/calendar/google_connection';
	
	//User Google Calendar Credential
	$config['google_calendar_redirect_uri_user'] = $config['base_url'].'user/calendar/google_connection';
	$config['email_send_from'] = 'smtp';
	//Google contact 
	
	/*$config['twitter_access_key'] = '8mZM4zKwB8XP3r9JA1bOqYFcF';
	$config['twitter_secret_key'] = 'twP9o04FQKPuwou5M3vgkaXqjJFZ6zK6baOsNGcoM53iXhYcfv';
	$config['twitter_callback_url'] = $config['base_url'].'admin/social_account_master/twitter_callback';*/

	//MlS database
	$config['mls_staging_db'] 		= 'livewire_staging_database';
	$config['mls_staging_host'] 	= 'localhost';
	$config['mls_staging_username'] = 'root';
	$config['mls_staging_password'] = '';

	$config['mls_master_db']  		= 'livewire_master_database';
	$config['mls_master_host']  	= 'localhost';
	$config['mls_master_username']  = 'root';
	$config['mls_master_password']  = '';

	$config['ns_record_details'] = 'ns1.localhost.com<br>ns2.localhost.com';

}

// Mail Gun Credential
$config['domain'] = 'mylivewiresolution.com';
$config['domain_key'] = 'key-6ch4ac-kvtc81pta1rrgqkcnv9xcsct1';

//cdn credencial
$config['cdn_username'] = 'briandeacon';
$config['cdn_api_key']  = 'c1cf0f7bdbfe704cf61c1440a0050501';
// Property Image URL
$config['NWMLS'] = 'http://405076f95bbea2ca5eea-06da07d5a4c9721bbebebda5153c82b5.r41.cf2.rackcdn.com/property_image/';
$config['Asheville'] = 'http://wncrmls.thelivewiresolution.com/IMG-';
$config['Florida'] = 'http://beachesmls.thelivewiresolution.com/IMG-';
$config['Portland'] = 'http://rmls.thelivewiresolution.com/IMG-';